version: 2
jobs:
  build-code:
    docker:
      - image: petewall/platformio
    steps:
      - checkout
      - run:
          command: pio pkg update
          name: Updating platformio
      - run: 
          command: pio check --skip-packages -v --project-conf=platformio.ini --fail-on-defect=medium --fail-on-defect=high
          name: Check defects >= medium
      - run:
          command: pio run --environment=DEBUG
          name: Build-DEBUG 
      - run:
          command: pio run --environment=RELEASE
          name: Build-RELEASE
      - run:
          command: pio test --environment=DEBUG
          name: Run Unit Tests
      - run:
          command: cppcheck --enable=all --inconclusive --error-exitcode=1 src/
          name: Static Code Analysis
      - store_artifacts:
          path: .pio/build
          destination: build-artifacts
workflows:
  build:
    jobs:
    - build-code
  version: 2